---
title: "Tree Growth Submodels for the US Northern Forest"
subtitle: "Results and Analysis"
author: "Neal Maker & John Foppert"
date: "`r lubridate::today()`"
output: 
  pdf_document:
    fig_caption: TRUE
    df_print: kable
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE, cache = TRUE)

library("here")
library("tidyverse")
library("pdp")
library("caret")
library("kableExtra")
library("extrafont")
library("pROC")

load("C:/Users/Neal/projects/big-rdas/mort-model-full.rda")
load("C:/Users/Neal/projects/big-rdas/dbh-growth-model-full.rda")
load("C:/Users/Neal/projects/big-rdas/cr-growth-model-full.rda")
load("C:/Users/Neal/projects/big-rdas/ht-model-full.rda")
```

```{r results='asis'}
tibble(variable = rownames(varImp(dbh_growth_model_full)$importance),
                 dbh_growth = varImp(dbh_growth_model_full)$importance$Overall,
                 height = varImp(ht_model_full)$importance$Overall,
                 cr_growth = varImp(cr_growth_model_full)$importance$Overall,
                 mort = varImp(mort_model_full)$importance$Overall[-1],
                 mean = (dbh_growth + height + cr_growth + mort)/4) %>% 
  arrange(desc(mean)) %>% 
  select(-mean) %>%
  mutate(variable = gsub("_", " ", variable)) %>% 
  mutate_if(is.numeric, function(x) {
    cell_spec(round(x), background = spec_color(x, option = "C"))
  }) %>% 
  kable(booktabs = T, escape = F, linesep = "",
        align = c("l", "c", "c", "c", "c"),
        col.names = c("variable",
                      "$\\Delta$dbh",
                      "height",
                      "$\\Delta$cr",
                      "survival"),
        caption = "Scaled variable importance measures for predictors in individual submodels. Calculated on out of bag data using 'impurity' measure. The most important predictor for each model is ranked 100 and the least important is ranked 0.") %>% 
  add_header_above(c(" " = 1, "submodel" =  4)) %>% 
  kable_styling(latex_options = "hold_position")
```
.
\pagebreak

#Diameter Growth Submodel

```{r, results='asis'}
getTrainPerf(dbh_growth_model_full)[,1:3] %>% 
  kable(booktabs = T, linesep = "", digits = c(6,3,6),
        col.names = c("RMSE", "R^2", "MAE"),
        caption = "Accuracy estimates, calculated on out of bag data") %>% 
  kable_styling(position = "center",
                latex_options = "hold_position")
```

```{r, fig.cap="Overall error distribution estimated with kernal density."}
error <- tibble(spp = dbh_growth_model_full$trainingData$spp, 
              y = dbh_growth_model_full$trainingData$.outcome,
              y_hat = dbh_growth_model_full$finalModel$predictions,
              err = y - y_hat)

error %>% ggplot(aes(err)) +
  geom_density(fill = "dark gray") +
  xlab("error (in/yr)") +
  theme(text = element_text(family = "Perpetua"))
```

```{r, fig.cap="Error distributions for individual species estimated with kernal density. Blue vertical lines indicate 0 (no error). Brown vertical lines indicate mean species errors."}
error %>% 
  group_by(spp) %>% 
  mutate(err_mean = mean(err)) %>% 
  ungroup() %>% 
  ggplot(aes(err)) +
  geom_density(fill = "dark gray") +
  xlab("error (in/yr)") +
  theme(text = element_text(family = "Perpetua"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(limits = c(0,200),
                     breaks = c(0,100,200)) +
  scale_x_continuous(breaks = c(-0.04, 0, 0.04),
                     limits = c(-0.04, 0.04)) +
  geom_vline(xintercept = 0, col = "#386cb0", size = 1) +
  geom_vline(aes(xintercept = err_mean), col = "#bf5b17", size = 1) +
  facet_wrap(~ spp)
```

```{r, results='asis'}
spp_RMSE <- error %>% 
  group_by(spp) %>% 
  summarize(n = n(), nRMSE = 0) %>% 
  arrange(desc(n))

for (i in 1:length(spp_RMSE$spp)){
  x <- filter(error, spp == spp_RMSE$spp[[i]])
  spp_RMSE[i, 3] <- RMSE(x$y, x$y_hat)/mean(x$y)
}

kable(spp_RMSE, booktabs = T, linesep = "", digits = 4,
      caption = "Sample sizes and normalized root mean square errors by species") %>% 
  kable_styling(latex_options = "hold_position")
```

<!-- ##Partial dependence plots for individual predictors -->

```{r, fig.height=4}
# for(i in 1:length(predictors(dbh_growth_model_full))){
#   x <- pdp::partial(dbh_growth_model_full, 
#                     pred.var = predictors(dbh_growth_model_full)[[i]], 
#                     plot = T, plot.engine = "ggplot2")
#   
#   print(x)
# }
```
.
\pagebreak

#Height Submodel

```{r, results='asis'}
getTrainPerf(ht_model_full)[,1:3] %>% 
  kable(booktabs = T, linesep = "", digits = c(2,3,2),
        col.names = c("RMSE", "R^2", "MAE"),
        caption = "Accuracy estimates, calculated on out of bag data") %>% 
  kable_styling(position = "center",
                latex_options = "hold_position")
```

```{r, fig.cap="Overall error distribution estimated with kernal density."}
error <- tibble(spp = ht_model_full$trainingData$spp, 
              y = ht_model_full$trainingData$.outcome,
              y_hat = ht_model_full$finalModel$predictions,
              err = y - y_hat)

error %>% ggplot(aes(err)) +
  geom_density(fill = "dark gray") +
  xlab("error (feet)") +
  theme(text = element_text(family = "Perpetua"))
```

```{r, fig.cap="Error distributions for individual species estimated with kernal density. Blue vertical lines indicate 0 (no error). Brown vertical lines indicate mean species errors."}
error %>% 
  group_by(spp) %>% 
  mutate(err_mean = mean(err)) %>% 
  ungroup() %>% 
  ggplot(aes(err)) +
  geom_density(fill = "dark gray") +
  xlab("error (feet)") +
  theme(text = element_text(family = "Perpetua"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_vline(xintercept = 0, col = "#386cb0", size = 1) +
  geom_vline(aes(xintercept = err_mean), col = "#bf5b17", size = 1) +
  facet_wrap(~ spp)
```

```{r, results='asis'}
spp_RMSE <- error %>% 
  group_by(spp) %>% 
  summarize(n = n(), nRMSE = 0) %>% 
  arrange(desc(n))

for (i in 1:length(spp_RMSE$spp)){
  x <- filter(error, spp == spp_RMSE$spp[[i]])
  spp_RMSE[i, 3] <- RMSE(x$y, x$y_hat)/mean(x$y)
}

kable(spp_RMSE, booktabs = T, linesep = "", digits = 4,
      caption = "Sample sizes and normalized root mean square errors by species") %>% 
  kable_styling(latex_options = "hold_position")
```

<!-- ##Partial dependence plots for individual predictors -->

```{r, fig.height=4}
# for(i in 1:length(predictors(ht_model_full))){
#   x <- pdp::partial(ht_model_full, 
#                     pred.var = predictors(ht_model_full)[[i]], 
#                     plot = T, plot.engine = "ggplot2")
#   
#   print(x)
# }
```
.
\pagebreak

#Crown Ratio Change Submodel

```{r, results='asis'}
getTrainPerf(cr_growth_model_full)[,1:3] %>% 
  kable(booktabs = T, linesep = "", digits = c(2,3,2),
        col.names = c("RMSE", "R^2", "MAE"),
        caption = "Accuracy estimates, calculated on out of bag data") %>% 
  kable_styling(position = "center",
                latex_options = "hold_position")
```

```{r, fig.cap="Overall error distribution estimated with kernal density."}
error <- tibble(spp = cr_growth_model_full$trainingData$spp, 
              y = cr_growth_model_full$trainingData$.outcome,
              y_hat = cr_growth_model_full$finalModel$predictions,
              err = y - y_hat)

error %>% ggplot(aes(err)) +
  geom_density(fill = "dark gray") +
  xlab("error (%change/yr)") +
  theme(text = element_text(family = "Perpetua"))
```

```{r, fig.cap="Error distributions for individual species estimated with kernal density. Blue vertical lines indicate 0 (no error). Brown vertical lines indicate mean species errors."}
error %>% 
  group_by(spp) %>% 
  mutate(err_mean = mean(err)) %>% 
  ungroup() %>% 
  ggplot(aes(err)) +
  geom_density(fill = "dark gray") +
  xlab("error (%change/yr)") +
  theme(text = element_text(family = "Perpetua"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_vline(xintercept = 0, col = "#386cb0", size = 1) +
  geom_vline(aes(xintercept = err_mean), col = "#bf5b17", size = 1) +
  facet_wrap(~ spp)
```

```{r, results='asis'}
spp_RMSE <- error %>% 
  group_by(spp) %>% 
  summarize(n = n(), nRMSE = 0) %>% 
  arrange(desc(n))

for (i in 1:length(spp_RMSE$spp)){
  x <- filter(error, spp == spp_RMSE$spp[[i]])
  spp_RMSE[i, 3] <- RMSE(x$y, x$y_hat)/mean(x$y)
}

kable(spp_RMSE, booktabs = T, linesep = "", digits = 4,
      caption = "Sample sizes and normalized root mean square errors by species") %>% 
  kable_styling(latex_options = "hold_position")
```

<!-- ##Partial dependence plots for individual predictors -->

```{r, fig.height=4}
# for(i in 1:length(predictors(cr_growth_model_full))){
#   x <- pdp::partial(cr_growth_model_full, 
#                     pred.var = predictors(cr_growth_model_full)[[i]], 
#                     plot = T, plot.engine = "ggplot2")
#   
#   print(x)
# }
```
.
\pagebreak

#Survival Submodel

```{r, results='asis'}
y <- mort_model_full$trainingData$.outcome
y_hat <- predict(mort_model_full, newdata = mort_model_full$trainingData[,-18])
y_hat_prob <- predict(mort_model_full, 
                      newdata = mort_model_full$trainingData[,-18],
                      type = "prob")

cm <- confusionMatrix(data = y_hat, reference = y, positive = "lived") # Calculate CM

cm$overall %>% 
  kable(booktabs = T, linesep = "", digits = 3,
        caption = "Overall accuracy estimates, calculated on out of bag data") %>% 
  kable_styling(position = "center",
                latex_options = "hold_position")
```

```{r, results='asis'}
cm$byClass %>% 
  kable(booktabs = T, linesep = "", digits = 3,
        caption = "Accuracy estimates by class, calculated on out of bag data") %>% 
  kable_styling(position = "center",
                latex_options = "hold_position")
```

```{r, results='asis'}
cm$table %>% 
  kable(booktabs = T, linesep = "",
        caption = "Confusion matrix. Columns are actual, observed outcomes; rows are predicted outcomes.") %>% 
  kable_styling(position = "center",
                latex_options = "hold_position")
```

```{r}
result.roc <- roc(y, y_hat_prob$lived) # Calculate ROC curve

plot(result.roc, print.auc = T) #plot ROC with AUC on it
```

<!-- ##Partial dependence plots for individual predictors -->

```{r, fig.height=4}
# for(i in 1:length(predictors(mort_model_full))){
#   x <- pdp::partial(ht_model_full, 
#                     pred.var = predictors(ht_model_full)[[i]], 
#                     plot = T, plot.engine = "ggplot2")
#   
#   print(x)
# }
```